### ISSUE TITLE
Does not work with query parameters without values

### ISSUE THREAD

**Issue by Rhincodon** [spatie/url#10]
When we trying to parse `http://test.com/test?a=1&b` or `http://test.com/test?a=1&b&c=1` it returns error `[2017-03-09 12:07:21] local.ERROR: ErrorException: Undefined offset: 1 in vendor/spatie/url/src/Helpers/Arr.php:19
`

**Comment by sebastiandedeyne** [comment]
Fixed in v1.0.2!
