### ISSUE TITLE
Ability to configure `VALID_SCHEMES` or disable scheme validation

### ISSUE THREAD

**Issue by bmitch** [spatie/url#24]
Really enjoy using this package and been using it for a number of projects. 

Ran into a situation where some of the URLs I need to work with have a scheme of `applewebdata`.

This fails when I attempt to make a URL with this scheme since the only schemes allowed are:

```
    const VALID_SCHEMES = ['http', 'https', 'mailto'];
```

However, there are many more valid schemes than those 3:

https://tools.ietf.org/html/rfc3986#section-3.1

I'd like to make a PR to solve this situation but wanted to run this by you guys to discuss what the best solution would be before I do any coding. Some ideas are:

* A: Removing the scheme validation altogether. 
* B: Or maybe make it something that can be turned off.
* C: Adjusting the scheme validation to use the pattern describes in that RFC.

Thanks very much.

**Comment by freekmurze** [comment]
I'd like to go for option B and D. D = making the schemes configurable.

**Comment by niocncn** [comment]
Have the same issue. I had exception in case of `android-app://...` that is default referrer in Android WebView. Make please some method like `isUrlValid` that return bool or a way to disable checking schemes.
