### ISSUE TITLE
Full example in the introduction to spatie/url

### ISSUE THREAD

**Issue by klor** [spatie/url#27]
This may be obvious to most, but I think the [introduction](https://github.com/spatie/url/blob/master/README.md) would benefit from a full example on how to use this package, example:

```php
<?php
require 'vendor/autoload.php';

use Spatie\Url\Url;

$url = Url::fromString('https://spatie.be/opensource');

echo $url->getScheme(); // 'https'
echo $url->getHost(); // 'spatie.be'
echo $url->getPath(); // '/opensource'
```

Happy Coding!

**Comment by freekmurze** [comment]
Feel free to send a PR! 👍

**Comment by klor** [comment]
no idea how to do that, but the full example exists now.. ;-)
