### ISSUE TITLE
Leading slash in path

### ISSUE THREAD

**Issue by bessone** [spatie/url#36]
Hello,

I started using this library in a Laravel project.

The request's path method in Laravel does not include the leading slash in the returned value (https://laravel.com/docs/7.x/requests#request-path-and-method), the path method in this library include it.

I understand that this library is not directly connected with Laravel, but is it conceivable to standardize it? Or create a new method or option on the existing method?

Thanks!

**Comment by freekmurze** [comment]
For now, we're not going to change this, as a few other packages depend on the current behaviour.
