### ISSUE TITLE
Duplicate question mark for query params

### ISSUE THREAD

**Issue by homayoonahmadi** [spatie/url#50]
Hi there. I recently used your library and I found that there is a problem with question mark(?) at the end of the url.

If we use a base url that already contains query parameters like : `https://example.com/?param=test` and add parameters using `withQueryParameter('key','value')` function, then it appends a new question mark that makes url not valid. in this example it will looks like:
`https://example.com/?param=test?key=value`

But it have to be:
`https://example.com/?param=test&key=value`
cause only the first ? is significant to web browsers.

Solution: You only have to change 3 lines in `__toString()` method:

```
        if ($this->getQuery() !== '') {
            if (\Str::contains($url, '?'))
                $url .= '&';
            else
                $url .= '?';

            $url .= $this->getQuery();
        }
```

I already extended your Url class in MyUrl class to fix the bug for now. 
Please fix this or let me know if your not going to improve the library. Thanks in advance.

**Comment by freekmurze** [comment]
This should be fixed in the latest release.
