### ISSUE TITLE
Android app link

### ISSUE THREAD

**Issue by sruns** [spatie/url#64]
Hello, 
I’m using your package to manipulate and validate urls coming from a tracking script. 
And I have started getting an erros because some of the url where coming from android apps with ‘android-app://com.google.android.gm/’ referrer link.

Error: Spatie\Url\Exceptions\InvalidArgument: The scheme `android-app` isn't valid. It should be either `http`, `https`, `mailto` or `tel`.

Ofcorse I can write condition but also I think it should be supported in this package.
What do you think?

**Comment by freekmurze** [comment]
Feel free to send a PR
